### ISSUE TITLE
运行出错显示lic_url为空

### ISSUE THREAD

**Issue by aeioudaa** [CrymanChen/WKS-KEYS#12]
大佬大佬，我在使用时遇到了点问题，希望大佬解答（Windows）
以下是使用步骤

1.将widevinecdm.dll文件放在WKS-KEYS\pywidevine\L3\cdm\devices\android_generic文件夹下

2.找到mpd的License_url以及mpd中的pssh填写在l3.py中（24行无需变动）
![企业微信截图_17286182593198](https://github.com/user-attachments/assets/4dde138e-1020-4f8b-9185-43ca0801bbab)

3.curl（base）格式复制License_url，放在https://curlconverter.com/ 中取headers放在headers.py文件中
![111 (2)](https://github.com/user-attachments/assets/ae27feae-ce73-4b04-b4dd-53a247929cb1)

4.python打开l3.py运行
![企业微信截图_17286186159982](https://github.com/user-attachments/assets/2dabe587-0f30-48fc-b922-fc0fcd6206e3)

得到的结果为我输入的pssh
那就是说
![image](https://github.com/user-attachments/assets/222f9104-8a9e-4c0f-8890-4cb1dbae5196)
这一步key没取到吗，哪里出现了问题

**Comment by aeioudaa** [comment]
好吧，是我的错，上述运行并不完全，出来一个新的错误
![image](https://github.com/user-attachments/assets/d7c3ce48-48fd-4fec-977e-19a9edd8860e)
no client ID blob available for this device
Traceback (most recent call last):
  File "C:\Users\Moyea\Desktop\N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG\pywidevine-1.8.0-py3-none-any\WKS-KEYS\l3.py", line 40, in <module>
    correct, keys = WV_Function(pssh, lic_url)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Moyea\Desktop\N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG\pywidevine-1.8.0-py3-none-any\WKS-KEYS\l3.py", line 26, in WV_Function
    widevine_license = requests.post(url=lic_url, data=wvdecrypt.get_challenge(), headers=headers.headers)
  File "C:\Users\Moyea\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Moyea\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moyea\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\Moyea\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
    ~~~~~~~~~^
        method=request.method.upper(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        hooks=merge_hooks(request.hooks, self.hooks),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Moyea\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Moyea\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
    ...<2 lines>...
    )
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

大概意思是说l3.py的第26行中的lic_url为空,我在第22行已近赋值了,为什么到26行会为空

**Comment by CrymanChen** [comment]
不是哥们，你认真的吗？

先不说你用IDLE运行一个如此复杂的程序，你这个
`pssh = input('AAAAAUHBzcGzAAA...FUrISEQ=')`
以及
`lic_url = input('https://udrmv3.kaltura.com/cenc/widevine/license?custom_data=...')`
你这是在干什么？如果你不了解Python，请你自行花点时间去学

还有这一步
> 1.将widevinecdm.dll文件放在WKS-KEYS\pywidevine\L3\cdm\devices\android_generic文件夹下

请问这是在干什么？如果你已经能直接把ChromeCDM拿过来用了，请让我跟随您学习好吗
[使用方法](https://github.com/CrymanChen/WKS-KEYS?tab=readme-ov-file#usage-chinese-simplified)中已提示
> 本项目需要一定的专业知识(A bit technical), 如果您对该领域不了解, 请不要进行尝试, 我亦不会对相应问题进行解答, 敬请谅解。

没有任何问题
![20241011-215411](https://github.com/user-attachments/assets/64ae79b5-6505-4807-ae41-b2ce07c6805f)
这是你需要的密钥：

> --key 2efd6c3f7bc60beab83198b603150aff:ca48d3468a1c1ae8138aa14b74a9fb0c
