### ISSUE TITLE
Error due to own problems (CDM not properly implemented)

### ISSUE THREAD

**Issue by deathnoragami** [CrymanChen/WKS-KEYS#15]
```
PSSH: AAAAoXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAIEIARIQzJ0aYvMBMomkHlIOU6mbaxoIY2FzdGxhYnMiWGV5SmhjM05sZEVsa0lqb2lPRFV4T1RkaE16UXhNV1l4WWpNMU1qbGlabU15T0dFMU1qTTNNalEzWmpjaUxDSjJZWEpwWVc1MFNXUWlPaUpoZG10bGVTSjkyB2RlZmF1bHQ=
License URL: https://cr-license-proxy.prd.crunchyrollsvc.com/v1/license/widevine
no client ID blob available for this device
Traceback (most recent call last):
  File "C:\Python\cdm\l3.py", line 38, in <module>
    correct, keys = WV_Function(pssh, lic_url)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\cdm\l3.py", line 24, in WV_Function
    widevine_license = requests.post(url=lic_url, data=wvdecrypt.get_challenge(), headers=headers.headers)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 366, in request
    chunks_and_cl = body_to_chunks(body, method=method, blocksize=self.blocksize)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ankot\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\request.py", line 247, in body_to_chunks
    raise TypeError(
TypeError: 'body' must be a bytes-like object, file-like object, or iterable. Instead was 1


```

**Comment by CrymanChen** [comment]
**Reason**: CDM not placed properly. (**_NOT MY PROBLEM_**)

**Sequences**: 
1. You do not have a CDM, and you didn't place your CDM into the WKS-KEYS.
2. Due to no CDM, the _challenge_ can not be generated, which is the _body_ (_payload_) of the `widevine_license`
3. Even though there is no _challenge_, the program still tried to send the request to the server. However, error occurred because of the absence of _challenge_, instead there is a sole "1".
4. The program finally exited with the error you presented.

I also tried to examine other parts of the data you input. PSSH was correct: 



    PSSH Box v0
    System ID: Widevine edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
    PSSH Data (size: 129):
        Widevine Data:
          Key IDs (1):
            cc9d1a62-f301-3289-a41e-520e53a99b6b
          Provider: castlabs
          Content ID: 65794A6863334E6C64456C6B496A6F694F4455784F5464684D7A51784D575978596A4D314D6A6C695A6D4D794F4745314D6A4D334D6A51335A6A63694C434A3259584A7059573530535751694F694A68646D746C65534A39
          Policy: default

And the License URL seems to be no problems.

**Solutions**: 
Place your own CDM in the folder below: 
`pywidevine\L3\cdm\devices\android_generic`
**Remember, THIS PROJECT does not provide CDM.**
